### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by christophetd** [ControlCompass/ControlCompass.github.io#1]
Hi! Great project. Eager to add some of the TTPs we have in https://github.com/DataDog/stratus-red-team

What's the best way to contribute?

**Comment by jorgeorchilles** [comment]
I would like to do the same. What is the best way to contribute?

**Comment by christophetd** [comment]
I ended PM'ing the author on Twitter

**Comment by jorgeorchilles** [comment]
Thanks, I just DMed @IntelScott Did you get a response?

**Comment by ControlCompass** [comment]
Thanks both for reaching out! Glad we could connect. Yes, for now my preferred way to get new datasets into the project is to connect so we can coordinate on formatting. Yes, Twitter is best: https://twitter.com/IntelScott

Hoping to streamline this in the future. For now the main focus is bringing more datasets in generally, and refining the web app/outputs.

Thank you again!
