### ISSUE TITLE
Still providing updates?

### ISSUE THREAD

**Issue by dr4lekhine** [ControlCompass/ControlCompass.github.io#5]
Hello,

First of all, thank you for sharing this with the community. Is a ver good tool for Threat Intel and for network defenders.

Also, I would like to know if you still continue updating this repo/tool, or is already deprecated and you are totally advocated to Tidal Cyber Community Edition?. Could you also enumerate the differences between that platform (community edition) and this tool?, and also the advantages of that platform?
https://app.tidalcyber.com/

Thanks in advance.

Regards.

**Comment by tropChaud** [comment]
Thanks for the positive feedback! Much appreciated. The web app and this repo will remain up but the underlying data is no longer being updated (updates were infrequent anyway). Advantages of the Tidal Community Edition include: superior and more useable UI, regular data updates, and defensive/control mapping sources beyond open-source/public repositories (e.g. provided directly by partner vendors). And new mapping sources continue to be added too.

**Comment by ControlCompass** [comment]
Thanks for the positive feedback! Much appreciated. The web app and this repo will remain up but the underlying data is no longer being updated (updates were infrequent anyway). Advantages of the Tidal Community Edition include: superior and more useable UI, regular data updates, and defensive/control mapping sources beyond open-source/public repositories (e.g. provided directly by partner vendors). And new mapping sources continue to be added too.
